### ISSUE TITLE
Adding Elements in with conditional does not work as expected

### ISSUE THREAD

**Issue by karlderkaefer** [crossplane-contrib/function-kcl#160]
### What happened?

I have problems to use arrays with conditionals. I would like add an element to an array, but the output is not as expected

### How can we reproduce it?

This KCL script 

```kcl
# Define schemas
schema PolicyStatement:
    Sid: str
    Effect: str
    Action: [str]
    Resource: [str]

schema PolicyDocument:
    Version: str = "2012-10-17"
    Statement: [PolicyStatement]

_s3_statement = PolicyStatement {
    Sid = "AllowS3Read"
    Effect = "Allow"
    Action = [
        "s3:GetObject"
        "s3:GetObjectVersion"
        "s3:ListBucket"
        "s3:ListBucketVersions"
    ]
    Resource = ["arn:aws:s3:::mybucket/*"]
}

_statement_custom_key_1 = PolicyStatement {
    Sid = "AllowKMSDecryptCustomKey"
    Effect = "Allow"
    Action = ["kms:Decrypt"]
    Resource = ["arn:aws:kms:::alias/custom-key"]
}

_statement_custom_key_2: PolicyStatement = PolicyStatement {
    Sid = "AllowKMSDecryptCustomKey2"
    Effect = "Allow"
    Action = ["kms:Decrypt"]
    Resource = ["arn:aws:kms:::alias/custom-key2"]
}

_statements: [PolicyStatement] = [_s3_statement]

if False:
    _statements += [_statement_custom_key_1]
if True:
    _statements += [_statement_custom_key_2]

items = [
    PolicyDocument {
        Statement = _statements
    }
]
```

is producing following output 
```yaml
items:
- Version: '2012-10-17'
  Statement:
  - Sid: AllowS3Read
    Effect: Allow
    Action:
    - s3:GetObject
    - s3:GetObjectVersion
    - s3:ListBucket
    - s3:ListBucketVersions
    Resource:
    - arn:aws:s3:::mybucket/*
  - Sid: AllowKMSDecryptCustomKey2
    Effect: Allow
    Action:
    - kms:Decrypt
    Resource:
    - arn:aws:kms:::alias/custom-key2
  - Sid: AllowKMSDecryptCustomKey2
    Effect: Allow
    Action:
    - kms:Decrypt
    Resource:
    - arn:aws:kms:::alias/custom-key2
```
the second element is duplicated, I would expect that the custom-key2 only is generated once in the output

### What environment did it happen in?

This happens with `xpkg.upbound.io/crossplane-contrib/function-kcl:v0.9.4` as well on command line with my example

Function version: 

```
kcl --version
kcl version 0.9.4
```
