### ISSUE TITLE
Extra resources with matchName does not work

### ISSUE THREAD

**Issue by irizzant** [crossplane-contrib/function-kcl#172]
### What happened?

I have the following Extra Resources defined 
```
_items = [{
    apiVersion = "meta.krm.kcl.dev/v1alpha1"
    kind = "ExtraResources"
    requirements = {
        test = {
            apiVersion = "platform.eng.it/v1alpha1"
            kind = "Project"
            matchName = "example-project"
        }
    }
}]
```
which matches the following project definition:
```yaml
apiVersion: platform.eng.it/v1alpha1
kind: Project
metadata:
  name: example-project
  namespace: default
  spec:
```

I then try to use this resource inside a Composition like this:
```
name = er?.test[0]?.Resource?.metadata?.name if er?.test else ""

_items += [
        {
            apiVersion = "repo.github.upbound.io/v1alpha1"
            kind = "Repository"
            metadata = _metadata("repository", "app") | {
                labels = {
                    "test" = name
                }
            }
        }
]
```
But the end result is that the test annotation is empty in my kubernetes cluster:
```yaml
apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  labels:
    test: ""
```
Instead, when I try to run `crossplane beta render` and specify the following manifest as extra resource:
```yaml
apiVersion: platform.eng.it/v1alpha1
kind: Project
metadata:
  name: example-project
  namespace: default
```

I get a different result and the annotation is loaded:
```yaml
apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  
  labels:
    test2: example-project
```

### What environment did it happen in?
Function version:
