### ISSUE TITLE
Values written in  context in first step is not available in the next

### ISSUE THREAD

**Issue by spastorclovr** [crossplane-contrib/function-kcl#200]
### What happened?

Step 1 of my function is writting to the pipeline context like so 

```
  _ctx = option("params").ctx
  _ctx.namespace = "mynamespace"
```
I can display the value of option("params").ctx inside the step1 but not in a step further down with the following code 

```
 _ctx = option("params").ctx
 items = [{ctx = _ctx}]

```
the context is then empty. 

### What environment did it happen in?
Function version: 0.10.10

**Comment by spastorclovr** [comment]
Sorry @Peefy for not including this before. 
Here is the steps as defined in my composition 


```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: generic-app-definition
spec:
  compositeTypeRef:
    apiVersion: apps.xxxx.tech/v1alpha1
    kind: XRApp
  mode: Pipeline
  pipeline:
  - step: step1
    functionRef:
      name: kcl-function
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      spec:
        dependencies: |
          k8s="1.31"
          crossplane-provider-kubernetes="0.9.2"
        source: |
          _ctx = option("params").ctx
          _ctx.namespace = "mynamespace"
          object = {
             apiVersion: "nopexample.org/v1"
             metadata.name = "object from step1"
             metadata.namespace = _ctx.namespace
             spec = {
             }
          }
          items = [object]
          
   - step: step2
    functionRef:
      name: kcl-function
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      spec:
        dependencies: |
          k8s="1.31"
          crossplane-provider-kubernetes="0.9.2"
        source: |
          _ctx = option("params").ctx
          object = {
             apiVersion: "nopexample.org/v1"
             metadata.name = "object from step2"
             metadata.namespace = _ctx.namespace
             spec = {
             }
          }

          items = [object]
```
The output from `crossplane render`


```
---
apiVersion: apps.chainstar.tech/v1alpha1
kind: App
metadata:
  name: myapp
status:
  conditions:
  - lastTransitionTime: "2024-01-01T00:00:00Z"
    message: 'Unready resources: object from step1, object from step2'
    reason: Creating
    status: "False"
    type: Ready
---
apiVersion: nopexample.org/v1
metadata:
  annotations:
    crossplane.io/composition-resource-name: object from step1
  generateName: myapp-
  labels:
    crossplane.io/composite: myapp
  name: object from step1
  namespace: mynamespace
  ownerReferences:
  - apiVersion: apps.chainstar.tech/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: App
    name: myapp
    uid: ""
spec: {}
---
apiVersion: nopexample.org/v1
metadata:
  annotations:
    crossplane.io/composition-resource-name: object from step2
  generateName: myapp-
  labels:
    crossplane.io/composite: myapp
  name: object from step2
  ownerReferences:
  - apiVersion: apps.chainstar.tech/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: App
    name: myapp
    uid: ""
spec: {}

```

:point_up:  I would expect a the "mynamespace" value in the metadata.namespace property from "Object from step2"
