### ISSUE TITLE
"krm.kcl.dev/ready" = "True" not working

### ISSUE THREAD

**Issue by vfarcic** [crossplane-contrib/function-kcl#201]
### What happened?

I have a resource with the annotation `"krm.kcl.dev/ready" = "True"` but the Composition still thinks that it is not ready.

```sh
crossplane beta trace --namespace a-team appclaim silly-demo
```

The output:

```
NAME                                  SYNCED   READY   STATUS
AppClaim/silly-demo (a-team)          True     False   Waiting: Claim is waiting for composite resource to become Ready
└─ App/silly-demo-gh5v2               True     False   Creating: Unready resources: silly-demo-provider-config-kubernetes
   ├─ Object/silly-demo-deployment    True     True    Available
   ├─ Object/silly-demo-hpa           True     True    Available
   ├─ Object/silly-demo-ingress       True     True    Available
   ├─ Object/silly-demo-service       True     True    Available
   └─ ProviderConfig/silly-demo-app   -        -
```

The XR complaints about `silly-demo-provider-config-kubernetes` which is `ProviderConfig/silly-demo-app` in the list below it and is the one with the annotation.

Here's the output from `kubectl describe providerconfigs.kubernetes.crossplane.io silly-demo-app` that shows that the annotation is indeed there.

```
Name:         silly-demo-app
Namespace:    
Labels:       crossplane.io/claim-name=silly-demo
              crossplane.io/claim-namespace=a-team
              crossplane.io/composite=silly-demo-gh5v2
Annotations:  crossplane.io/composition-resource-name: silly-demo-provider-config-kubernetes
              krm.kcl.dev/ready: True
API Version:  kubernetes.crossplane.io/v1alpha1
Kind:         ProviderConfig
Metadata:
  Creation Timestamp:  2024-11-29T16:37:05Z
  Finalizers:
    in-use.crossplane.io
  Generate Name:  silly-demo-gh5v2-
  Generation:     1
  Owner References:
    API Version:           devopstoolkitseries.com/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  App
    Name:                  silly-demo-gh5v2
    UID:                   a48a28f5-eab9-4a71-b731-0f369cb51484
  Resource Version:        25281
  UID:                     27373ba8-2a7d-43a3-bd54-257c3e883d4b
Spec:
  Credentials:
    Source:  InjectedIdentity
Status:
  Users:  4
Events:   <none>
```

Composition code:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: app-backend
  labels:
    type: backend
    location: local
spec:
  compositeTypeRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: App
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  mode: Pipeline
  pipeline:
  - step: kcl
    functionRef:
      name: crossplane-contrib-function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLRun
      metadata:
        name: kubernetes
      spec:
        target: Resources
        source: |+
          oxr = option("params").oxr
          dxr = {
              **oxr
              status.host = oxr.spec.parameters.host
          }

          schema providerConfig:
              _apiVersion: str
              _suffix: str
              apiVersion = _apiVersion
              kind = "ProviderConfig"
              metadata = {
                  name = oxr.spec.id + "-app"
                  annotations = {
                      "krm.kcl.dev/ready" = "True"
                      "krm.kcl.dev/composition-resource-name" = oxr.spec.id + "-provider-config-" + _suffix
                  }
              }
              spec = {
                  credentials.source = "InjectedIdentity"
              }

          _items = [
              providerConfig {
                  _apiVersion = "kubernetes.crossplane.io/v1alpha1"
                  _suffix = "kubernetes"
              } , {
                  apiVersion = "kubernetes.crossplane.io/v1alpha1"
                  kind = "Object"
                  metadata.name = "{}-deployment".format(oxr.spec.id)
                  spec = {
                      forProvider.manifest = {
                          apiVersion = "apps/v1"
                          kind = "Deployment"
                          metadata = {
                              name = oxr.spec.id
                              namespace = oxr.spec.parameters.namespace
                              labels = {
                                  "app.kubernetes.io/name" = oxr.spec.id
                              }
                          }
                          spec = {
                              selector.matchLabels = {
                                  "app.kubernetes.io/name" = oxr.spec.id
                              }
                              template = {
                                  metadata.labels = {
                                      "app.kubernetes.io/name" = oxr.spec.id
                                  }
                                  spec = {
                                      containers = [{
                                          image = oxr.spec.parameters.image
                                          name = "backend"
                                          ports = [{containerPort = 80 }]
                                          livenessProbe = {
                                              httpGet = {
                                                  path = "/"
                                                  port = oxr.spec.parameters.port
                                              }
                                          }
                                          readinessProbe = {
                                              httpGet = {
                                                  path = "/"
                                                  port = oxr.spec.parameters.port
                                              }
                                          }
                                          resources = {
                                              limits = {cpu = "250m", memory = "256Mi" }
                                              requests = {cpu = "125m", memory = "128Mi" }
                                          }
                                          ports = [
                                              {containerPort = oxr.spec.parameters.port }
                                          ]
                                          if oxr.spec.parameters?.db?.secret:
                                              env = [
                                                  {
                                                      name = "DB_ENDPOINT"
                                                      valueFrom.secretKeyRef = {
                                                          key = "endpoint"
                                                          name = oxr.spec.parameters.db.secret
                                                      }
                                                  }, {
                                                      name = "DB_PASSWORD"
                                                      valueFrom.secretKeyRef = {
                                                          key = "password"
                                                          name = oxr.spec.parameters.db.secret
                                                      }
                                                  }, {
                                                      name = "DB_PORT"
                                                      valueFrom.secretKeyRef = {
                                                          key = "port"
                                                          name = oxr.spec.parameters.db.secret
                                                          optional = True
                                                      }
                                                  }, {
                                                      name = "DB_USERNAME"
                                                      valueFrom.secretKeyRef = {
                                                          key = "username"
                                                          name = oxr.spec.parameters.db.secret
                                                      }
                                                  }, {
                                                      name = "DB_NAME"
                                                      value = oxr.spec.id
                                                  },
                                              ]
                                      }]
                                  }
                              }
                          }
                      }
                      providerConfigRef.name = oxr.spec.id + "-app"
                  }
              }, {
                  apiVersion = "kubernetes.crossplane.io/v1alpha1"
                  kind = "Object"
                  metadata.name = "{}-service".format(oxr.spec.id)
                  spec = {
                      forProvider.manifest = {
                          apiVersion = "v1"
                          kind = "Service"
                          metadata = {
                              name = oxr.spec.id
                              namespace = oxr.spec.parameters.namespace
                              labels = {
                                  "app.kubernetes.io/name" = oxr.spec.id
                              }
                          }
                          spec = {
                              type = "ClusterIP"
                              ports = [{
                                  port = oxr.spec.parameters.port
                                  targetPort = oxr.spec.parameters.port
                                  protocol = "TCP"
                                  name = "http"
                              }]
                              selector = {
                                  "app.kubernetes.io/name" = oxr.spec.id
                              }
                          }
                      }
                      providerConfigRef.name = oxr.spec.id + "-app"
                  }
              }, {
                  apiVersion = "kubernetes.crossplane.io/v1alpha1"
                  kind = "Object"
                  metadata.name = "{}-ingress".format(oxr.spec.id)
                  spec = {
                      forProvider.manifest = {
                          apiVersion = "networking.k8s.io/v1"
                          kind = "Ingress"
                          metadata = {
                              name = oxr.spec.id
                              namespace = oxr.spec.parameters.namespace
                              labels = {
                                  "app.kubernetes.io/name" = oxr.spec.id
                              }
                              annotations = {"ingress.kubernetes.io/ssl-redirect" = "false" }
                          }
                          spec = {
                              if oxr.spec.parameters?.ingressClassName:
                                  ingressClassName = oxr.spec.parameters.ingressClassName
                              rules = [{
                                  host = oxr.spec.parameters.host
                                  http = {
                                      paths = [{
                                          path = "/"
                                          pathType = "ImplementationSpecific"
                                          backend.service = {
                                              name = oxr.spec.id
                                              port.number = oxr.spec.parameters.port
                                          }
                                      }]
                                  }
                              }]
                          }
                      }
                      providerConfigRef.name = oxr.spec.id + "-app"
                  }
              }
          ]

          if oxr.spec.parameters?.scaling?.enabled:
              _items += [{
                  apiVersion = "kubernetes.crossplane.io/v1alpha1"
                  kind = "Object"
                  metadata.name = "{}-hpa".format(oxr.spec.id)
                  spec = {
                      forProvider.manifest = {
                          apiVersion = "autoscaling/v2"
                          kind = "HorizontalPodAutoscaler"
                          metadata = {
                              name = oxr.spec.id
                              namespace = oxr.spec.parameters.namespace
                              labels = {
                                  "app.kubernetes.io/name" = oxr.spec.id
                              }
                          }
                          spec = {
                              scaleTargetRef = {
                                  apiVersion = "apps/v1"
                                  kind = "Deployment"
                                  name = oxr.spec.id
                              }
                              minReplicas = oxr.spec.parameters.scaling.min
                              maxReplicas = oxr.spec.parameters.scaling.max
                              metrics = [{
                                  type = "Resource"
                                  resource = {
                                      name = "cpu"
                                      target = {
                                          type = "Utilization"
                                          averageUtilization = 80
                                      }
                                  }
                              }, {
                                  type = "Resource"
                                  resource = {
                                      name = "memory"
                                      target = {
                                          type = "Utilization"
                                          averageUtilization = 80
                                      }
                                  }
                              }]
                          }
                      }
                      providerConfigRef.name = oxr.spec.id + "-app"
                  }
              }]

          items = _items

  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: crossplane-contrib-function-auto-ready
```

The output of `crossplane render...`

```yaml
---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
status:
  conditions:
  - lastTransitionTime: "2024-01-01T00:00:00Z"
    message: 'Unready resources: silly-demo-deployment, silly-demo-hpa, silly-demo-ingress,
      and 2 more'
    reason: Creating
    status: "False"
    type: Ready
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/composition-resource-name: silly-demo-deployment
  generateName: silly-demo-
  labels:
    crossplane.io/composite: silly-demo
  name: silly-demo-deployment
  ownerReferences:
  - apiVersion: devopstoolkitseries.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: AppClaim
    name: silly-demo
    uid: ""
spec:
  forProvider:
    manifest:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app.kubernetes.io/name: silly-demo
        name: silly-demo
        namespace: a-team
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: silly-demo
        template:
          metadata:
            labels:
              app.kubernetes.io/name: silly-demo
          spec:
            containers:
            - image: vfarcic/silly-demo:1.0.8
              livenessProbe:
                httpGet:
                  path: /
                  port: 8080
              name: backend
              ports:
              - containerPort: 8080
              readinessProbe:
                httpGet:
                  path: /
                  port: 8080
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
                requests:
                  cpu: 125m
                  memory: 128Mi
  providerConfigRef:
    name: silly-demo-app
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/composition-resource-name: silly-demo-hpa
  generateName: silly-demo-
  labels:
    crossplane.io/composite: silly-demo
  name: silly-demo-hpa
  ownerReferences:
  - apiVersion: devopstoolkitseries.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: AppClaim
    name: silly-demo
    uid: ""
spec:
  forProvider:
    manifest:
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        labels:
          app.kubernetes.io/name: silly-demo
        name: silly-demo
        namespace: a-team
      spec:
        maxReplicas: 5
        metrics:
        - resource:
            name: cpu
            target:
              averageUtilization: 80
              type: Utilization
          type: Resource
        - resource:
            name: memory
            target:
              averageUtilization: 80
              type: Utilization
          type: Resource
        minReplicas: 2
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: silly-demo
  providerConfigRef:
    name: silly-demo-app
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/composition-resource-name: silly-demo-ingress
  generateName: silly-demo-
  labels:
    crossplane.io/composite: silly-demo
  name: silly-demo-ingress
  ownerReferences:
  - apiVersion: devopstoolkitseries.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: AppClaim
    name: silly-demo
    uid: ""
spec:
  forProvider:
    manifest:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        annotations:
          ingress.kubernetes.io/ssl-redirect: "false"
        labels:
          app.kubernetes.io/name: silly-demo
        name: silly-demo
        namespace: a-team
      spec:
        rules:
        - host: silly-demo.54.159.206.46.nip.io
          http:
            paths:
            - backend:
                service:
                  name: silly-demo
                  port:
                    number: 8080
              path: /
              pathType: ImplementationSpecific
  providerConfigRef:
    name: silly-demo-app
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  annotations:
    crossplane.io/composition-resource-name: silly-demo-provider-config-kubernetes
    krm.kcl.dev/ready: "True"
  generateName: silly-demo-
  labels:
    crossplane.io/composite: silly-demo
  name: silly-demo-app
  ownerReferences:
  - apiVersion: devopstoolkitseries.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: AppClaim
    name: silly-demo
    uid: ""
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/composition-resource-name: silly-demo-service
  generateName: silly-demo-
  labels:
    crossplane.io/composite: silly-demo
  name: silly-demo-service
  ownerReferences:
  - apiVersion: devopstoolkitseries.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: AppClaim
    name: silly-demo
    uid: ""
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        labels:
          app.kubernetes.io/name: silly-demo
        name: silly-demo
        namespace: a-team
      spec:
        ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
        selector:
          app.kubernetes.io/name: silly-demo
        type: ClusterIP
  providerConfigRef:
    name: silly-demo-app
```

### How can we reproduce it?

I provided all the code and outputs above. The code itself is in the https://github.com/vfarcic/crossplane-app repo. KCL code is in `kcl` and the rendered Composition is in `package`.

### What environment did it happen in?

Function version: 
kcl v0.10.10 (I tried with the older version first and it wasn't working with it either).
