### ISSUE TITLE
Ability to import different kcl files based on parameters

### ISSUE THREAD

**Issue by irizzant** [crossplane-contrib/function-kcl#204]
### What happened?

I'd like to specify a `channel` parameter that can be read in my Composition file, and decide what file to import basing on that parameter. 
Something like:

```yaml
apiVersion: krm.kcl.dev/v1alpha1
kind: KCLInput
metadata:
  annotations:
    "krm.kcl.dev/default_ready": "True"
  name: basic
spec:
  source: |
    import file

    if _option("params")?.oxr?.spec.parameters.channel:
       file.read(_option("params")?.oxr?.spec.parameters.channel + "/something.yaml"
    else:
       file.read("default/somethingElse.yaml")
```
but maybe it's not feasible.

### What environment did it happen in?
Function version:
