### ISSUE TITLE
Is there a way to login to a private OCI to retrieve dependency modules

### ISSUE THREAD

**Issue by spastorclovr** [crossplane-contrib/function-kcl#213]
### What problem are you facing?

I would like to be able to use modules stored in a private registry. 
By specifiying the module like so :point_down: 

 kcl-package = { oci = "oci://registry.gitlab.com/xxx/xxx/infra-experiment/kcl-package", tag = "0.0.1"}
 
 Using  the `credentials` property does not seem to do the trick. 
 
 Is there a way to perform something equivalent to a `docker login` ?

**Comment by zong-zhe** [comment]
Hi @spastorclovr 😄 

Use `kcl registry login`, the usage is similar to `docker login`.

https://www.kcl-lang.io/docs/tools/cli/package-management/command-reference/login

**Comment by spastorclovr** [comment]
Hey thx @zong-zhe  :smile: 
How would you perform `kcl registry login` in the context of a function? Would it require to create a brand new docker image to handle this step?
thx again.

**Comment by archae0pteryx** [comment]
Any updates on this?

**Comment by maulik13** [comment]
This is very much needed. If we are packaging a composition using multiple KCL files and publishing this package we need a way to login to the registry from the KCL function.

**Comment by cjuega** [comment]
Facing the same problem here. Is there any workaround? Otherwise using kcl modules is not an option with this Crossplane function 😢.

**Comment by spastorclovr** [comment]
I solved this by passing as env variables those values 👇 directly to the KCL function runtime itself.

KCL_SRC_URL=https://registry.gitlab.com
KCL_SRC_USERNAME=<Username with RO to the registry>
KCL_SRC_PASSWORD=<PASSWORD>

You would need to use a Crossplane DeploymentRuntimeConfig to modify the KCL function definition.
Something like this

```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: kcl
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - env:
            - name: KCL_SRC_URL
              value: https://registry.gitlab.com
            - name: KCL_SRC_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: <your secret >
            - name: KCL_SRC_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: <yoursecret>
            name: package-runtime
```


Once you've done that, in your composition 

```
API Version:  krm.kcl.dev/v1alpha1                                                                                                  
Kind:         KCLInput                                                                                                               
Spec:                                                                                                                              
         Source:  oci://registry.gitlab.com/XXX/XXX//kcl-functions/app?tag=0.0.5
```

Here the **app** module will be successfully downloaded and any dependencies it uses as well, provided that they come from the same registy.
