### ISSUE TITLE
Cannot use credentials to authenticate with a gitlab source repository

### ISSUE THREAD

**Issue by spastorclovr** [crossplane-contrib/function-kcl#219]
Not sure whether this is should be a bug or a feature request, as the only example shown for source credentials is for OCI registries. 

I did try to use the "credentials" specs targeting an gitlab repo, and it does not work.

```
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      spec:
        credentials:
          username: XXX
          #password: <gitlab project token>
          url: gitlab.com/<path to repo> <-- does not seem to be used
        source: gitlab.com/<path to repo>

```
It does not work and the errors is as folow

```
t': /usr/bin/git exited with 128: fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
```
