### ISSUE TITLE
How to import common schemas?

### ISSUE THREAD

**Issue by irizzant** [crossplane-contrib/function-kcl#235]
Hi,

I have some KCL code which I'd like to reuse, for example some schemas.

How would I reuse it in function-kcl?

**Comment by maulik13** [comment]
KCL itself allows you to get modules from a remote repository. We use the dependency field to point to a GitHub repo which hosts the KCL modules with common schemas and utilities. 

Here is an example, https://github.com/vfarcic/crossplane-sql/blob/main/kcl/compositions.k#L36

This requires setting up access to GitHub private repository which is not easy to do using functions-kcl. We ended up using DeploymentRuntimeConfig for function-kcl pod which provides Git config to access private repos using an init container. 

Here is our runtime config
```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: fn-kcl
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          volumes:
            # Shared volume for the git configuration file
            - name: git-config
              emptyDir: {}
          initContainers:
            - name: init-gitconfig
              image: alpine:3.16
              volumeMounts:
                - name: git-config
                  mountPath: /config
              command:
                - /bin/sh
                - -c
                - |
                  # Write the git configuration file with the desired content.
                  # The file is created at /config/gitconfig so that the main container can use it.
                  mkdir /config/git
                  cat <<EOF > /config/git/config
                  [credential "https://github.com"]
                    username = infra-bot
                    helper = "!f() { test \"\$1\" = get && echo \"password=\${GITHUB_TOKEN}\"; }; f"
                  EOF
          containers:
            - name: package-runtime
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: gitsecret
                      key: password
              volumeMounts:
                - name: git-config
                  mountPath: /.config

```
