### ISSUE TITLE
Name conflict for resources of Different Kinds

### ISSUE THREAD

**Issue by patryk-przekwas-airspace-intelligence** [crossplane-contrib/function-kcl#241]
### What happened?
While generating resources with KCL, I encountered an issue where creating resources with the same name (but of different types) resulted in the removal of duplicated names from the output. There were no errors during the process, making debugging quite difficult. I expected the function to return a complete list of resources, as the resource types were different despite having the same name.

I found an issue that describes pretty much the same problem. It was closed, but it seems the problem still persists: https://github.com/crossplane-contrib/function-kcl/issues/91

### How can we reproduce it?
Go to https://github.com/crossplane-contrib/function-kcl/tree/main/examples/resources/network and modify `composition.yaml` to duplicate name:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xlabels.fn-demo.crossplane.io
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: fn-demo.crossplane.io/v1alpha1
    kind: XNetwork
  mode: Pipeline
  pipeline:
  - step: normal
    functionRef:
      name: kcl-function
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        name: basic
      spec:
        target: Resources
        source: |
          # Get the XR spec fields
          id = option("params")?.oxr?.spec.id or ""
          # Render XR to crossplane managed resources
          network_id_labels = {"networks.meta.fn.crossplane.io/network-id" = id} if id else {}
          vpc = {
              apiVersion = "ec2.aws.upbound.io/v1beta1"
              kind = "VPC"
              metadata.name = "vpc"
              metadata.labels: network_id_labels
              spec.forProvider = {
                  region = "eu-west-1"
                  cidrBlock = "192.168.0.0/16"
                  enableDnsSupport = True
                  enableDnsHostnames = True
              }
          }
          gateway = {
              apiVersion = "ec2.aws.upbound.io/v1beta1"
              kind = "InternetGateway"
              metadata.name = "vpc"
              metadata.labels: network_id_labels
              spec.forProvider = {
                  region = "eu-west-1"
                  vpcIdSelector.matchControllerRef = True
              }
          }
          items = [vpc, gateway]
```
Output of `crossplane render xr.yaml composition.yaml functions.yaml -r` looks as follows:
```yaml
---
apiVersion: fn-demo.crossplane.io/v1alpha1
kind: Network
metadata:
  name: network-test-functions
status:
  conditions:
  - lastTransitionTime: "2024-01-01T00:00:00Z"
    message: 'Unready resources: vpc'
    reason: Creating
    status: "False"
    type: Ready
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  annotations:
    crossplane.io/composition-resource-name: vpc
  generateName: network-test-functions-
  labels:
    crossplane.io/composite: network-test-functions
    networks.meta.fn.crossplane.io/network-id: network-test-functions
  name: vpc
  ownerReferences:
  - apiVersion: fn-demo.crossplane.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: network-test-functions
    uid: ""
spec:
  forProvider:
    region: eu-west-1
    vpcIdSelector:
      matchControllerRef: true

```
As you can see the VPC resource is missing.

### What environment did it happen in?
Function version: `main`

* Running `function-kcl` locally on my M1 mac
* Kernel `Darwin ASI-J4WN77WP43 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:23 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6020 arm64`
