### ISSUE TITLE
Reference KCLInput in the Composition from in cluster.

### ISSUE THREAD

**Issue by archae0pteryx** [crossplane-contrib/function-kcl#260]
### What problem are you facing?
In my compositions, I would like to be able to reference a KCLInput that is already applied in cluster instead of mounting a cm or referencing an external git/oci repo.

```yaml
kind: Composition
  # ...
  mode: Pipeline
  pipeline:
    - step: basic
      functionRef:
        name: function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1 # side note: this seems to be the wrong group/version now?
        kind: KCLInput
        sourceRef:
          name: basic # something like this
```

The development feedback loop for these functions hurt... Maybe I don't have the proper dev flow figured out yet?

### How could this Function help solve your problem?
If i could reference my KCLInput CRD in my composition directly instead of inlining I would be able to better revise and develop these.

Thanks for your work!
