### ISSUE TITLE
Example input missing `spec`

### ISSUE THREAD

**Issue by negz** [crossplane-contrib/function-kcl#262]
### What happened?

As of ee7ef3e the first example in `README.md` is this:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: basic
      functionRef:
        name: function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        source: |
          # KCL input goes here...
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
```

Notice `source` is at the root of the `KCLInput`. This doesn't work. `function-kcl` expects it to be nested under `spec`, like this:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: basic
      functionRef:
        name: function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        spec:
          source: |
            # KCL input goes here...
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
```

FWIW the example _without_ spec is more idiomatic. All other Crossplane Functions that I'm aware of don't use `spec`. For example:

```yaml
apiVersion: python.fn.crossplane.io/v1beta1
kind: Script
script: |
  # Some python...
```

```yaml
apiVersion: pt.fn.crossplane.io/v1beta1
kind: Resources:
resources:
- base:
     # Some YAML...
```

Many of the other examples also show a `KCLInput` with a `metadata.name`. There's no reason to include this - Crossplane will ignore it.
