### ISSUE TITLE
Pass existing secret to credential for kcl function

### ISSUE THREAD

**Issue by doncorsean** [crossplane-contrib/function-kcl#272]
For sourcing code/dependencies from private OCI registries would it make sense to add a field called credentialsSecret to ref an existing secret. Would facilitate 12h auto-generation of ECR cred with external secrets ECR generator and keep cred pw out of kcl manifest. 

```
spec:
  credentials:
    url: <account>.dkr.ecr.<region>.amazonaws.com
    username: "AWS"
    password: "secret"
```
vs.
```
spec:
  credentialSecret: my-secret
```

**Comment by doncorsean** [comment]
@vfarcic is this something you think is worthwhile?

**Comment by aaronborden-rivianvw** [comment]
A little under documented, but I believe Crossplane has support for passing secrets to functions via the pipeline step [credentials](https://docs.crossplane.io/v2.0/api/#Composition-spec-pipeline-credentials). I think what's missing is that function-kcl needs to read the credentials passed to it and document how to name the credential.

In theory, this should work, but currently does not.
`crossplane render --function-credentials=secret.yaml examples/claim.yaml package/apis/composition.yaml examples/functions.yaml`

```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xredis.aws.cloudinfra.rivian.com
spec:
  compositeTypeRef:
    apiVersion: aws.swi.rivianvw.tech/v1alpha1
    kind: XRedis
  mode: Pipeline
  pipeline:
    - step: kcl-transform
      functionRef:
        name: crossplane-contrib-function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        spec:
          source: oci://ghcr.io/example/kcl
      credentials:
        - name: kcl-registry
          source: Secret
          secretRef:
            namespace: default
            name: default
---
apiVersion: v1
kind: Secret
metadata:
  name: default
  namespace: default
type: Opaque
dataString:
  url: https://example.com
  username: user
  password: password
```
