### ISSUE TITLE
[Enhancement] Support annotation to set the plain http for the crossplane kcl function

### ISSUE THREAD

**Issue by Peefy** [crossplane-contrib/function-kcl#47]
### What problem are you facing?

OCI Source is managed by function kcl and should be able to be set through the fields of KCLRun, in theory something like this perhaps.

```yaml
    functionRef:
      name: kcl-function
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLRun
      metadata:
        name: basic
        annotations:
          kcl-something/allow-insecure-source: True
      spec:
        target: Resources
        source: oci://localhost:7900/my-composition-kcl:0.0.1
```

**Comment by Peefy** [comment]
More information can be found here https://github.com/crossplane-contrib/function-kcl/issues/43#issuecomment-2006852958

**Comment by markphillips100** [comment]
Hi @Peefy.  When can we expect a release with this PR?

**Comment by Peefy** [comment]
Hi @markphillips100 I've released function-kcl v0.3.3 for this issue. When we close this local path import issue https://github.com/kcl-lang/krm-kcl/issues/42 and we will release v0.3.4

**Comment by markphillips100** [comment]
Thank you @Peefy

**Comment by markphillips100** [comment]
@Peefy I've just tried v0.3.3 using the below yaml and got into problems.

If I use `krm.kcl.dev/allow-insecure-source: true` and apply the composition manifest I get the familiar error `Invalid value: map[string]interface {}{"annotations":map[string]interface {}{"krm.kcl.dev/allow-insecure-source":true}, "name":"basic"}: json: cannot unmarshal bool into Go struct field ObjectMeta.annotations of type string`.

If I use `krm.kcl.dev/allow-insecure-source: "true"` then applying the composition gives no parsing error however the source request is still using https: `Get "https://host.docker.internal:7900/v2/tuckerbox/country-composition-kcl/tags/list": http: server gave HTTP response to HTTPS client` - note I am using host.docker.internal rather than localhost in order to access the host's docker registry.

Composition:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: my-composite
spec:
  compositeTypeRef:
    apiVersion: tuckerbox.com/v1alpha1
    kind: MyComposite
  mode: Pipeline
  pipeline:
  - step: normal
    functionRef:
      name: kcl-function
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLRun
      metadata:
        name: basic
        annotations:
          krm.kcl.dev/allow-insecure-source: "true"
      spec:
        target: Resources
        source: oci://host.docker.internal:7900/tuckerbox/my-composition-kcl:0.0.1
```

Function:
```
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: kcl-function
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-kcl:v0.3.3
```
