### ISSUE TITLE
Example KCL to pass resource data between created cloud resources

### ISSUE THREAD

**Issue by markphillips100** [crossplane-contrib/function-kcl#55]
I'm writing KCL code to create Azure resources using the KCL crossplane function as part of a composition.  I need to supply some of one resource's "atProvider" data to another resource's "forProvider" data.

In the past this would be achieved by using a patch with the patch and transform function but I would prefer to keep this encapsulated within the KCL code if possible.

Should I use the `option("params").ocds` some how to access the named resource and obtain its `atProvider` data?  If so, can you provide an example of accessing a a resource this way.  Please also let me know if this is not the preferred way of doing this.

**Comment by Peefy** [comment]
Do you mean this?

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-template-go
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: normal1
    functionRef:
      name: kcl-function
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLRun
      metadata:
        name: basic
      spec:
        target: Resources
        source: |
          {
              metadata.name = "resource1"
              spec.forProvider.network: "somenetwork"
          }
  - step: normal2
    functionRef:
      name: kcl-function
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLRun
      metadata:
        name: basic
      spec:
        target: Resources
        source: |
          {
              metadata.name = "resource2"
              spec.atProvider = option("params").dcds["resource1"].Resource.spec.forProvider
          }
```
