### ISSUE TITLE
Ability to decouple `metadata.name` from  `crossplane.io/composition-resource-name` and `crossplane.io/external-name` annotations

### ISSUE THREAD

**Issue by ytsarev** [crossplane-contrib/function-kcl#77]
### What problem are you facing?

Currently, in this function the `metadata.name` is a single entry point and identifier that is getting automatically propagated to  `crossplane.io/composition-resource-name` and `crossplane.io/external-name` annotations.

That is convenient but frequently undesired behavior.

The situations where it is required for them to have different values:

* I want to have the same `metada.name` across different resource kinds. Currently if I try to do it with function-kcl the resources with the same `metada.name` are getting overrides by the last one, because  the same `crossplane.io/composition-resource-name` is getting set automatically.
Example:
```
            providerConfigTypes = ["helm", "kubernetes"]
            providerConfigs = [{
              apiVersion = "{}.crossplane.io/v1alpha1".format(t)
              kind = "ProviderConfig"
              metadata.name = id
              metadata.annotations = {
                  "krm.kcl.dev/ready": "True"
              }
              spec.credentials = {
                  secretRef = {
                    name = "{}-ekscluster".format(uid)
                    namespace = connectionSecretNamespace
                    key = "kubeconfig"
                  }
                  source = "Secret"
                }
            } for t in providerConfigTypes]
```

Only last `kubernetes` ProviderConfig is getting rendered in this case

```
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  annotations:
    crossplane.io/composition-resource-name: configuration-aws-eks
```
because the function is setting identical `crossplane.io/composition-resource-name` annotation

* The case when we need to set `crossplane.io/external-name` different from `metadata.name` due to MR identifier specifics. It is requirement when the external resource identifier is not compliant with RFC 1123.
It frequently affects resources that has dots and other characters as part of their identifier like a domainname
https://marketplace.upbound.io/providers/upbound/provider-aws-apigatewayv2/v1.3.1/resources/apigatewayv2.aws.upbound.io/DomainName/v1beta1

```
apiVersion: apigatewayv2.aws.upbound.io/v1beta1
kind: DomainName
metadata:
  annotations:
    crossplane.io/external-name: example-email.upbound-providers.io
  name: example
spec:
  forProvider:
...
```
In this case `metada.name` != `crossplane.io/external-name` and it is mandatory. 
It is relatively frequent case when we need to override external-name.

### How could this Function help solve your problem?

Respect when user sets custom values like
```
metadata.annotations = {
    "crossplane.io/composition-resource-name" = "custom-composition-name"
    "crossplane.io/external-name" = "custom-external-name"
}
```

Currently they are getting overridden by `metadata.name` value and it breaks the desired behavior
