### ISSUE TITLE
Kind not considered in Items list

### ISSUE THREAD

**Issue by reedjosh** [crossplane-contrib/function-kcl#91]
### What happened?
I tried to create two resources with different kinds, but the same name.

``` kcl
        source: |
          oxr = option("params").oxr
          envconf = option("params").ctx["apiextensions.crossplane.io/environment"]
          items = [
            {
              apiVersion = "eks.aws.upbound.io/v1beta1"
              kind = "Cluster"
              metadata.name = oxr.metadata.labels["crossplane.io/claim-name"]
              metadata.labels = { "aws.platform.ripple.com/observedcluster" = "true" }
              spec = { 
                forProvider.region = oxr.spec.parameters.region
                providerConfigRef.name = envconf.name
                managementPolicies = ["Observe"]
              }
            },
            {
                apiVersion = "apiextensions.crossplane.io/v1alpha1"
                kind = "EnvironmentConfig"
                metadata.name = oxr.metadata.labels["crossplane.io/claim-name"]
                metadata.labels = { "aws.platform.ripple.com/observedcluster" = "true" }
            }
          ]

```

Output:
``` yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  annotations:
    crossplane.io/composition-resource-name: cluster-josh-x1
  generateName: cluster-josh-x1-
  labels:
    aws.platform.ripple.com/observedcluster: "true"
    crossplane.io/composite: cluster-josh-x1
  name: cluster-josh-x1
  ownerReferences:
    - apiVersion: aws.platform.ripple.com/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: ObservedCluster
      name: cluster-josh-x1
      uid: ""
spec:
  forProvider:
    region: us-west-2
  managementPolicies:
    - Observe
  providerConfigRef:
    name: dev2-us-west-2
```

I only get whatever the final object was instead of a `Cluster` and an `EnvironmentConfig`

### How can we reproduce it?
Attempt to create two different items with the same name.

Observe that the output is actually the merging of the two yaml objects instead of two distinct objects.

### What environment did it happen in?
Function version:  v0.7.0
